# Use an official NVIDIA CUDA base image compatible with CUDA 12.x
#FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04
FROM nvidia/cuda:12.0.1-cudnn8-devel-ubuntu22.04

# Set environment variables to prevent interactive prompts during installation.
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# Install system dependencies, including Python 3.10, pip, git, and nano.
RUN apt-get update && \
    apt-get install -y \
    python3.10 \
    python3-pip \
    git \
    nano \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container.
WORKDIR /app

# Clone the GitHub repository into the working directory.
RUN git clone https://github.com/amirreza1998/MRT-release .

# Create a directory for data within the working directory.
RUN mkdir data

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1

# Install the nightly build of PyTorch to support the latest GPU architectures
RUN python -m pip install --timeout=1000 --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121

# Then, install the other dependencies from the requirements.txt file.
RUN python -m pip install -r requirements.txt

# Set the default command to open a bash shell when the container starts.
CMD ["/bin/bash"]
